url:
baseurl:

# Site settings
title: SHIKI 65536
email: shiki65536@gmail.com
description: "A junior web developer and programmer. "

# Team names, titles and social links
people:
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Larry Parker
    pic: 2
    position: Lead Marketer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Diana Petersen
    pic: 3
    position: Lead Developer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/shiki65536
  - title: facebook
    url: https://www.facebook.com/shiki65536
  - title: linkedin
    url: https://www.linkedin.com/in/shih-chi-wen-690526211/
  - title: github
    url: http://github.com/shiki65536

# Postal address (add as many lines as necessary)
address:
  - line: Holman Hall HH 417, 38 College Walk
  - line: Clayton, Victoria, Australia

# Build settings
markdown: kramdown
permalink: pretty
